name: Package and deploy

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy - Create Bundles
      run: npx lerna run deploy:bundle --stream

    - name: Deploy - Create Template
      run: npx lerna run deploy:synth --stream

    - name: Deploy - Show Diff
      run: npx lerna run deploy:diff --stream

    - name: Deploy!
      run: npx lerna run deploy:deploy --stream
